server:
  port: 8080
spring:
  application:
    name: "NameProject"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  restconsumer:
    timeout: 5000
    base_url_token: "https://experian-latamb.oktapreview.com"
    base_url_recognize: "https://demo-servicesesb.datacredito.com.co:444"
    credentials:
      username: "2-890903938.4@demo.datacredito.com.co"
      password: "Bancolombia23"
      client_id: "0oahhikalqSmwVzco0h7"
      client_secret: "x05fXZUCC3cx0IGA4KxhefSBy0KuvxrZWhLEdkrf"

